language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
# command to install dependencies
install:
  - pip install -r server/requirements.txt
# command to run tests
script:

  - cd server/ && python -m unittest discover tests
